### ISSUE TITLE
Есть ошибка при запуске Shinobi

### ISSUE THREAD

**Issue by MaxBocharovDev** [funchaser/shinobi-webrtc-mod#1]
Воспользовался модом, но при входе в Shinobi возникает ошибка, не могу разобраться где её подправить

Error: Could not find the include file "blocks/topLeftMenu.ejs"
   at getIncludePath (/home/Shinobi/node_modules/ejs/lib/ejs.js:165:13)
   at includeSource (/home/Shinobi/node_modules/ejs/lib/ejs.js:309:17)
   at /home/Shinobi/node_modules/ejs/lib/ejs.js:745:26
   at Array.forEach (<anonymous>)
   at Template.generateSource (/home/Shinobi/node_modules/ejs/lib/ejs.js:721:15)
   at Template.compile (/home/Shinobi/node_modules/ejs/lib/ejs.js:574:12)
   at Object.compile (/home/Shinobi/node_modules/ejs/lib/ejs.js:392:16)
   at handleCache (/home/Shinobi/node_modules/ejs/lib/ejs.js:215:18)
   at tryHandleCache (/home/Shinobi/node_modules/ejs/lib/ejs.js:254:16)
   at View.exports.renderFile [as engine] (/home/Shinobi/node_modules/ejs/lib/ejs.js:485:10)
   at View.render (/home/Shinobi/node_modules/express/lib/view.js:135:8)
   at tryRender (/home/Shinobi/node_modules/express/lib/application.js:640:10)
   at Function.render (/home/Shinobi/node_modules/express/lib/application.js:592:3)
   at ServerResponse.render (/home/Shinobi/node_modules/express/lib/response.js:1012:7)
   at Object.s.renderPage (/home/Shinobi/libs/webServerPaths.js:47:13)
   at renderPage (/home/Shinobi/libs/webServerPaths.js:233:19)

**Comment by funchaser** [comment]
Привет! Какая версия Shinobi установлена V2 или V3 ? Мой патч только для V2 (В V3 все сильно переделано, нужно много исправлений)

**Comment by MaxBocharovDev** [comment]
Вот эта у меня ветка  https://gitlab.com/Shinobi-Systems/Shinobi/-/tree/507955f2f48b5fa6b0e80bcafb44094cec644ce2
Как ты оцениваешь трудоемкость такой работы? Три дня, неделя? Пиши на [max.bocharov@gmail.com](mailto:max.bocharov@gmail.com)

**Comment by MaxBocharovDev** [comment]
Как ты оцениваешь трудоемкость такой работы? Три дня, неделя?

**Comment by funchaser** [comment]
У тебя установлена последняя V3 - проблема в том, что она концептуально отличается от V2 - в V3 новые возможности типа WebRTC и т.п. оформляются плагинами. Практически - в V3 нужно написать плагин для WEbRTC с нуля.... Если хочется использовать WebRTC быстро - проще поставить себе V2.....

**Comment by MaxBocharovDev** [comment]
Подскажи, а как понять, где V2 версия лежит? Можешь дать ссылку

**Comment by funchaser** [comment]
git clone https://gitlab.com/Shinobi-Systems/Shinobi.git
cd Shinobi
git reset --hard
git checkout cd10e634272ab116a2f25f767f42bdd9f5b73b0b
